[package]
name = "adventofcode2019"
version = "0.1.0"
authors = ["Thomas Zumsteg <thomas.zumsteg@gmail.com>"]
edition = "2018"

[dependencies]
regex="1.1.0"

[lib]
name = "common"
path = "lib.rs"

[[bin]]
name = "day01"
path = "day01.rs"

[[bin]]
name = "day02"
path = "day02.rs"

